import { useMemo, useState } from 'react';
import type { Professor } from './types';
import { buildTemporalInstitutions, TEMPORAL_SOURCES, TEMPORAL_METHOD_COMPARISON } from './temporalInstitutions';
import './temporal-institutions.css';

type Props = { professors: Professor[]; releaseYear: number };
type Metric = 'active' | 'hyperedgeContinuity' | 'jaccard' | 'stageDiversity';
const subjects: Record<string, string> = { mathematics: '수학', physics: '물리학', chemistry: '화학', biology: '생물학' };
const num = (n: number) => n.toLocaleString('ko-KR');
const ratio = (n: number | null) => n === null ? '—' : `${(n * 100).toFixed(1)}%`;
function Cite({ id }: { id: string }) { const source = TEMPORAL_SOURCES.find(s => s.id === id)!; return <a href={source.url} target="_blank" rel="noreferrer">{source.authors} ({source.year}) ↗</a>; }

export default function TemporalInstitutionsPage({ professors, releaseYear }: Props) {
  const [subject, setSubject] = useState('');
  const [institutionId, setInstitutionId] = useState('');
  const [includeEstimated, setIncludeEstimated] = useState(true);
  const [includeInferredDepartments, setIncludeInferredDepartments] = useState(false);
  const [year, setYear] = useState<number | null>(null);
  const [metric, setMetric] = useState<Metric>('hyperedgeContinuity');
  const data = useMemo(() => buildTemporalInstitutions(professors, { releaseYear, subject, includeEstimated, includeInferredDepartments }), [professors, releaseYear, subject, includeEstimated, includeInferredDepartments]);
  const institution = data.institutions.find(i => i.id === institutionId) ?? [...data.institutions].sort((a, b) => b.eligiblePeople - a.eligiblePeople)[0];
  const years = institution?.years ?? [];
  const point = years.find(y => y.year === year) ?? [...years].reverse().find(y => y.active > 0) ?? years[years.length - 1];
  const metricLabel = { active: '기록상 활동 연구자', hyperedgeContinuity: '그룹 구성 연속성', jaccard: '전년 구성원 유사도', stageDiversity: '경력 단계 다양성' };
  const max = metric === 'active' ? Math.max(1, ...years.map(y => y.active)) : 1;
  const x = (index: number) => 70 + index * 1030 / Math.max(1, years.length - 1);
  const y = (value: number) => 290 - value / max * 230;
  let segments = '';
  let pen = false;
  years.forEach((p, index) => { const value = p[metric]; if (value === null) { pen = false; return; } segments += `${pen ? 'L' : 'M'}${x(index)},${y(value)} `; pen = true; });
  const reset = () => setYear(null);
  return <section className="temporal-page" aria-labelledby="ti-title">
    <header className="ti-intro"><p className="ti-kicker">기관의 시간적 특성</p><h1 id="ti-title">Temporal institutional profiles</h1><p>기관·학과의 연간 구성원을 하이퍼엣지로 묶어, 규모와 지속성, 경력 구성의 변화를 분석합니다.</p></header>
    <div className="ti-note"><strong>{releaseYear}년 명부에서 되짚은 경력입니다.</strong><span>과거 기관 전체의 인력 현황이 아닙니다. 표본에 남은 연구자들의 기록을 설명하며, 기관의 우열이나 인과관계를 뜻하지 않습니다.</span></div>
    <div className="ti-controls"><label><span>연구 분야</span><select value={subject} onChange={e => { setSubject(e.target.value); reset(); }}><option value="">전체 분야</option>{Object.entries(subjects).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label className="ti-institution"><span>기관</span><select value={institution?.id ?? ''} onChange={e => { setInstitutionId(e.target.value); reset(); }}>{data.institutions.map(i => <option key={i.id} value={i.id}>{i.label} · {i.country}</option>)}</select></label><div className="ti-checks"><label><input type="checkbox" checked={includeEstimated} onChange={e => { setIncludeEstimated(e.target.checked); reset(); }} />추정된 경력 기간 포함</label><label><input type="checkbox" checked={includeInferredDepartments} onChange={e => { setIncludeInferredDepartments(e.target.checked); reset(); }} />추론된 학과 포함</label></div></div>
    <div className="ti-coverage" aria-live="polite"><strong>분석에 포함된 연구자 {num(data.eligiblePeople)} / {num(data.cohortPeople)}명</strong><span>기간·국가·학과 조건 때문에 제외된 연구자 {num(data.excludedPeople)}명</span><span>기간 추정으로 제외된 경력 {num(data.coverage.excludedEstimatedIntervals)}건 · 학과 추론으로 제외된 경력 {num(data.coverage.excludedInferredDepartmentIntervals)}건</span></div>
    {institution && <section className="ti-panel" aria-labelledby="ti-school"><div className="ti-heading"><div><p className="ti-kicker">선택 기관</p><h2 id="ti-school">{institution.label}</h2><p>{institution.country === 'KR' ? '학교 + 학과가 같은 연구자를 연도별로 묶습니다.' : '같은 학교의 연구자를 연도별로 묶습니다.'} 조건에 맞는 연구자 {num(institution.eligiblePeople)}명.</p></div><span className="ti-badge">{includeInferredDepartments ? '추론 학과 포함' : '추론 학과 제외'}</span></div>
      {!point ? <div className="ti-empty"><strong>현재 기준에 맞는 경력 기록이 없습니다.</strong><p>이 기관의 기록은 추정 기간 또는 추론된 학과 때문에 제외되었을 수 있습니다. 위 옵션에서 포함 여부를 선택할 수 있습니다. 기록이 없다는 사실을 활동 인원이 0명이라는 뜻으로 해석하지 않습니다.</p></div> : <>
        <div className="ti-year-heading"><h3>{point.year}년의 기록</h3><label><span>살펴볼 연도</span><select aria-label="살펴볼 연도" value={point.year} onChange={e => setYear(Number(e.target.value))}>{years.map(p => <option key={p.year} value={p.year}>{p.year}</option>)}</select></label></div>
        <div className="ti-stats"><div><span>기록상 활동 연구자</span><strong>{num(point.active)}<small>명</small></strong><p>이 중 추정 기간만 있는 연구자 {num(point.estimatedOnly)}명</p></div><div><span>그룹 구성 연속성</span><strong>{ratio(point.hyperedgeContinuity)}</strong><p>δNOA · 전년도 그룹과의 구성원 겹침</p></div><div><span>동시기 그룹</span><strong>{num(point.hyperedges)}<small>개</small></strong><p>2명 이상인 기관 단위 · 최대 {num(point.largestHyperedge)}명</p></div><div><span>경력 단계 다양성</span><strong>{point.stageDiversity === null ? '—' : point.stageDiversity.toFixed(3)}</strong><p>박사·박사후·교수의 구성 균형 · 0–1</p></div></div>
        <div className="ti-chart-top"><h3>연도별 변화</h3><div role="group" aria-label="도표 지표 선택">{(['hyperedgeContinuity', 'active', 'jaccard', 'stageDiversity'] as Metric[]).map(m => <button key={m} aria-pressed={metric === m} onClick={() => setMetric(m)}>{metricLabel[m]}</button>)}</div></div>
        <div className="ti-chart-scroll" tabIndex={0} aria-label="기관별 연도 변화 도표. 아래 연도 선택과 표로도 탐색 가능"><svg viewBox="0 0 1150 350" role="img" aria-labelledby="ti-chart-title"><title id="ti-chart-title">{institution.label}의 {metricLabel[metric]} 추이</title>{[0, .25, .5, .75, 1].map(t => <g key={t}><line x1={70} x2={1100} y1={y(t * max)} y2={y(t * max)} stroke="#e6e8ea" /><text x={56} y={y(t * max) + 5} textAnchor="end">{metric === 'active' ? Math.round(t * max) : t.toFixed(2)}</text></g>)}{metric === 'active' && years.length > 1 && <path d={`${segments} L${x(years.length - 1)},290 L70,290 Z`} fill="#256ef4" fillOpacity=".08" />}<path d={segments} fill="none" stroke="#256ef4" strokeWidth={3} />{years.map((p, index) => (index === 0 || index === years.length - 1 || p.year % 10 === 0) && <text key={p.year} x={x(index)} y={325} textAnchor="middle">{p.year}</text>)}<line x1={x(years.indexOf(point))} x2={x(years.indexOf(point))} y1={40} y2={290} stroke="#163c7a" strokeDasharray="4 4" />{point[metric] !== null && <circle cx={x(years.indexOf(point))} cy={y(point[metric]!)} r={6} fill="#fff" stroke="#256ef4" strokeWidth={3} />}</svg></div>
        <label className="ti-slider"><span>{years[0].year}</span><input type="range" min={years[0].year} max={years[years.length - 1].year} value={point.year} aria-label="도표에서 살펴볼 연도" onChange={e => setYear(Number(e.target.value))} /><strong>{point.year}년</strong><span>{releaseYear}</span></label>
        <div className="ti-chart-foot">0명은 이 명부에서 해당 연도의 유효한 경력이 관측되지 않았다는 뜻입니다. 유사도·다양성을 계산할 분모가 없으면 도표를 비워 둡니다.</div>
        <div className="ti-detail-grid"><div><h3>관측된 경력 이동</h3><dl><div><dt>다른 유효 경력에서 유입</dt><dd>{point.entries === null ? '—' : `${num(point.entries)}명`}</dd></div><div><dt>다른 유효 경력으로 유출</dt><dd>{point.exits === null ? '—' : `${num(point.exits)}명`}</dd></div><div><dt>통합 승계로 이어진 유입 · 이직 제외</dt><dd>{num(point.mergerEntries)}명</dd></div><div><dt>통합 승계로 이어진 유출 · 이직 제외</dt><dd>{num(point.mergerExits)}명</dd></div><div><dt>이전 기록 없음 · 유입 미확정</dt><dd>{num(point.leftCensored)}명</dd></div><div><dt>후속 기록 없음 · 유출 미확정</dt><dd>{num(point.rightCensored)}명</dd></div></dl><p>전년도에서 선택 연도로 바뀌는 경계를 비교합니다. 개인 관측의 시작·끝을 신규 유입·퇴사로 세지 않으며, 공개 연도 이후의 유출은 계산하지 않습니다. 경상국립대 통합(2021년)과 강원대 통합(2026년) 이후 같은 사람의 인접 연도 기록이 승계 기관으로 이어지면 일반 유입·유출에서 제외하고 따로 셉니다. 기록이 빈 연도를 건너 연결하지 않습니다.</p></div><div><h3>그룹의 구성</h3><dl><div><dt>평균 하이퍼엣지 크기</dt><dd>{point.meanHyperedgeSize === null ? '—' : `${point.meanHyperedgeSize.toFixed(1)}명`}</dd></div><div><dt>학과 간 공통 구성원</dt><dd>{point.crossDepartmentPeople === null ? '계산 불가' : `${num(point.crossDepartmentPeople)}명 · ${ratio(point.crossDepartmentShare)}`}</dd></div><div><dt>학교 전체 구성원 유사도 · J</dt><dd>{ratio(point.jaccard)}</dd></div><div><dt>관측 구성원 변화도 · 1−J</dt><dd>{ratio(point.turnover)}</dd></div><div><dt>추론 학과가 포함된 연구자</dt><dd>{num(point.inferredDepartmentPeople)}명</dd></div></dl><p>국내외 모두 같은 해 둘 이상의 학과 기록에 속한 연구자를 중복 없이 셉니다. 과거 학교명과 연간 활동 집합은 보존하므로, 통합 승계는 유입·유출 집계에서만 제외합니다. 공동연구나 실제 교류의 증거로 해석하지 않습니다.</p></div></div>
        <details className="ti-table-details"><summary>연도별 수치 표로 보기</summary><div className="ti-table-scroll"><table><caption>선택 기관의 연간 관측 기록. —는 계산 불가 또는 관측 경계입니다.</caption><thead><tr><th>연도</th><th>연구자</th><th>그룹 연속성 δNOA</th><th>Jaccard</th><th>변화도</th><th>그룹 수</th><th>평균 크기</th><th>단계 다양성</th><th>유입</th><th>유출</th><th>통합 승계 유입/유출</th><th>이전/후속 미관측</th></tr></thead><tbody>{years.map(p => <tr key={p.year} className={p.year === point.year ? 'is-selected' : ''}><th><button onClick={() => setYear(p.year)}>{p.year}</button></th><td>{p.active}</td><td>{ratio(p.hyperedgeContinuity)}</td><td>{ratio(p.jaccard)}</td><td>{ratio(p.turnover)}</td><td>{p.hyperedges}</td><td>{p.meanHyperedgeSize?.toFixed(1) ?? '—'}</td><td>{p.stageDiversity?.toFixed(3) ?? '—'}</td><td>{p.entries ?? '—'}</td><td>{p.exits ?? '—'}</td><td>{p.mergerEntries} / {p.mergerExits}</td><td>{p.leftCensored} / {p.rightCensored}</td></tr>)}</tbody></table></div></details>
      </>}
    </section>}
    <section className="ti-selection" aria-labelledby="ti-selection-title"><p className="ti-kicker">문헌 비교와 방법 선정</p><h2 id="ti-selection-title">연간 그룹의 구성원 겹침을 주지표로 선택했습니다</h2><p>현재 자료는 현직 명부에서 복원한 경력 구간입니다. 관측 해상도와 중첩 소속의 범위를 기준으로 세 방법을 비교했습니다.</p><div className="ti-comparison-scroll"><table><caption>시계열 하이퍼그래프 연구 세 편의 현재 데이터 적합성</caption><thead><tr><th scope="col">문헌 · 방법</th><th scope="col">필요한 구조</th><th scope="col">현재 자료와의 적합성</th><th scope="col">결정 · 제한</th></tr></thead><tbody>{TEMPORAL_METHOD_COMPARISON.map(m => <tr key={m.id} className={m.selected ? 'ti-chosen-row' : ''}><th scope="row"><Cite id={m.id} /><span>{m.method}</span></th><td>{m.requirement}</td><td>{m.fit}</td><td>{m.selected && <strong className="ti-chosen-label">선정</strong>}{m.limit}</td></tr>)}</tbody></table></div><div className="ti-selected-method"><h3>구현한 수식 · Cauteruccio et al. (2026), §4.2.1</h3><p>G(t)는 한 학교의 t년 기관 단위별 구성원 집합 모음입니다. 국내외 모두 학교 안의 학과별 집합을 사용합니다. 학과 근거가 없는 구간은 비교하지 않습니다.</p><div className="ti-equation" aria-label="이전 그룹 각각의 최대 자카드 겹침 합과 현재 그룹 각각의 최대 자카드 겹침 합을 두 시점의 그룹 수 합으로 나눈 값">δNOA = [ Σ<sub>e∈G(t−1)</sub> max<sub>f∈G(t)</sub> J(e,f) + Σ<sub>f∈G(t)</sub> max<sub>e∈G(t−1)</sub> J(f,e) ] / [ |G(t−1)| + |G(t)| ]</div><p>양방향으로 가장 많이 겹치는 그룹을 찾아 평균합니다. 2명 이상인 그룹만 사용하고 동일한 구성원 집합은 한 번만 셉니다. 학과명과 무관하게 구성원 집합을 비교하므로, 같은 학과에 남아 있는 비율과 다릅니다. 한쪽에 비교할 그룹이 없으면 계산하지 않습니다. <Cite id="ren" /></p><p><strong>적용 범위:</strong> 수식은 원문 그대로 사용하고, 원문의 REN 이웃 추출을 학교별 연간 그룹 모음으로 바꾸었습니다. 일대일 대응을 강제하지 않으며, REN 전체 절차나 STABILITY 사건 분류를 구현한 것은 아닙니다.</p><p><strong>해석 제한:</strong> 한 학교에서 두 연도 모두 비교 가능한 그룹이 하나씩이면 δNOA는 그 두 그룹의 Jaccard와 같습니다. 국가와 무관하게 학과가 거의 겹치지 않으면 추가로 얻는 구조 정보는 제한적입니다. 추정 기간으로 유도된 지속성, 추론 학과, 관측 명부의 선택 편향은 그대로 남습니다.</p></div></section>
    <section className="ti-method" aria-labelledby="ti-method-title"><p className="ti-kicker">어떤 지표를 계산했나요?</p><h2 id="ti-method-title">최근 시계열 하이퍼그래프 연구에서 가져온 관점</h2><p>그룹 구성 연속성은 선정 논문의 δNOA 수식을 계산한 값입니다. Jaccard·규모·경력 단계 다양성은 해석을 돕는 기술통계이며, 고차 기억이나 hyper-core 점수를 대체하지 않습니다.</p><div className="ti-method-grid"><article><span>01</span><h3>기관 단위 × 연도</h3><p>e(u,t) = 해당 연도에 기관 단위 u의 경력이 기록된 연구자 집합. 국내외 모두 학교+학과 단위입니다. 같은 연구자·기관 단위·연도는 한 번만 셉니다. 2명 이상의 집합을 도표의 하이퍼엣지로 셉니다.</p><p>시간에 따라 바뀌는 그룹을 분석한다는 관점: <Cite id="memory" /></p></article><article><span>02</span><h3>연속성 · 구성원 변화</h3><p>J(t) = |A(t−1) ∩ A(t)| / |A(t−1) ∪ A(t)|. A(t)는 해당 학교에서 관측된 전체 연구자 집합입니다. 변화도는 1−J이며, 고용 유지율과 다릅니다. 두 해 모두 비어 있으면 계산하지 않습니다.</p><p>구성원의 부분 겹침을 통한 시간적 유사성: <Cite id="ren" /></p></article><article><span>03</span><h3>규모 · 단계 구성</h3><p>그룹 크기는 |e(u,t)|입니다. 단계 다양성은 H = −Σ p(s) log p(s) / log 3. 박사·박사후·교수의 세 범주를 고정하며, 동시 단계가 있으면 한 연구자의 질량 1을 균등 분할합니다.</p><p>규모와 구조의 시간적 변화를 함께 읽는 관점: <Cite id="cores" /></p></article></div><div className="ti-null"><strong>‘특징이 유의하다’고 주장하려면 한 단계가 더 필요합니다.</strong><p>경력 길이, 기관 규모, 연도별 관측량 등을 보존한 귀무모형과 비교해야 합니다. 현재 화면은 효과 검정이나 인과 추론을 수행하지 않습니다. 시간적 고차 구조의 귀무모형 설계: <Cite id="rhem" /></p></div></section>
    <section className="ti-sources"><h2>확인한 연구 문헌</h2><p>2026년 9월 8일까지 공개된 문헌 중 이 분석 설계와 직접 관련된 연구입니다.</p>{TEMPORAL_SOURCES.map(s => <article key={s.id}><span>{s.year}</span><div><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><p>{s.authors} · {s.journal}</p><p>{s.note}</p></div></article>)}</section>
  </section>;
}
